// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACH6kHBWl2fUjjv0F8Dyvyx_TuAOJ4rac',
    appId: '1:399437922547:web:e6b8bd74256f21b62ef786',
    messagingSenderId: '399437922547',
    projectId: 'firestore-720bc',
    authDomain: 'firestore-720bc.firebaseapp.com',
    storageBucket: 'firestore-720bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwbQvuGKuT9gNk9tiMDING-zAsXwRAvsw',
    appId: '1:399437922547:android:b794b973b6d014692ef786',
    messagingSenderId: '399437922547',
    projectId: 'firestore-720bc',
    storageBucket: 'firestore-720bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJv300mODqs4UyDGfC6MTYRinV2ZUL3M',
    appId: '1:399437922547:ios:62e65a8ae7689a082ef786',
    messagingSenderId: '399437922547',
    projectId: 'firestore-720bc',
    storageBucket: 'firestore-720bc.firebasestorage.app',
    iosBundleId: 'com.q.q.qqq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeJv300mODqs4UyDGfC6MTYRinV2ZUL3M',
    appId: '1:399437922547:ios:62e65a8ae7689a082ef786',
    messagingSenderId: '399437922547',
    projectId: 'firestore-720bc',
    storageBucket: 'firestore-720bc.firebasestorage.app',
    iosBundleId: 'com.q.q.qqq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACH6kHBWl2fUjjv0F8Dyvyx_TuAOJ4rac',
    appId: '1:399437922547:web:62b576f129e0f75b2ef786',
    messagingSenderId: '399437922547',
    projectId: 'firestore-720bc',
    authDomain: 'firestore-720bc.firebaseapp.com',
    storageBucket: 'firestore-720bc.firebasestorage.app',
  );
}
